adapter, update BR
- missing tcl-devel
- AUTO: -- src/tkimage/_imagingtk.c:19:16: fatal error: tk.h: No such file or directory
- AUTO: -- src/tkXcursor/_tkXcursor.c:20:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory